/*
 * This source file was generated by the Gradle 'init' task
 */
package gradleproject;
import javafx.application.Application;
import org.sqlite.core.DB;
import javafx.stage.Stage;
import gradleproject.config.DbConnect;

public class App extends Application {

    public void start (Stage stage){
        DbConnect.connection();
        stage.show();
    }
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        launch ();
    }
}